### ISSUE TITLE
[SSR] - async load data question

### ISSUE THREAD

**Issue by pivanov** [Brigad/ssr-starter-pack#5]
Hey,

First of all great starter :)

I'm new to SSR and I just wanna ask something ...
Can we load async data for example on componentDidMount and then send it as HTML to client?

Thanks in advance! :)

**Comment by adrienharnay** [comment]
Hey, thank you!

`componentDidMount` will only be called on the client, but there are other ways to load data on the server and send it to the client! I'm not an expert in the matter, but the idea would be to have an async method on your route components, call all the methods of the routes you would need to render, wait for the data to be loaded, and then send the HTML to the server.

Hope it helps a bit :)
